image: python2.7
script: 
  - sudo apt-get -y install sqlite3 python-pip python-dev build-essential 1> /dev/null 2> /dev/null
  - pip install -r requirements.txt
  - make test
notify:
  email:
    recipients:
      - kevin@stealsyour.pw
